<link href="../css/ebaui_default.css" rel="stylesheet" type="text/css" />
<link href="../css/ebaui.datagrid.css" rel="stylesheet" type="text/css" />
<style type="text/css">pre { border-left : 5px solid #6CE26C; }</style>
<script src="../ebaui.lib.js" type="text/javascript" ></script>
<script src="../ebaui.js" type="text/javascript" ></script>
<script src="../ebaui.templates.js" type="text/javascript" ></script>
<script src="../ebaui.datagrid.js" type="text/javascript" ></script>