// Generated by CoffeeScript 1.7.1
module.exports = function(grunt) {
  return grunt.config('compress', {
    release: {
      options: {
        mode: 'zip',
        archive: '../release/<%=pkg.name%>-<%=pkg.version%>.zip'
      },
      files: [
        {
          src: ['**'],
          expand: true,
          cwd: '../release/<%=pkg.version%>/'
        }
      ]
    }
  });
};
