// Generated by CoffeeScript 1.7.1
module.exports = function(grunt) {
  var cat, css, cssfiles, cssname, filename, js, jsfiles, _ref;
  css = ['lib/jqGrid/css/jquery-ui-custom.css', 'lib/jqGrid/css/ui.multiselect.css', 'lib/jqGrid/css/ui.jqgrid.css'];
  cat = (_ref = grunt.config('concat')) != null ? _ref : {};
  if (cat["css"] == null) {
    cat["css"] = {
      files: {}
    };
  }
  cssname = "ebaui.datagrid.css";
  cssfiles = cat["css"]['files'];
  cssfiles["build/css/" + cssname] = css;
  cssfiles["../release/" + (grunt.config('pkg.version')) + "/css/" + cssname] = css;
  js = ['lib/jqGrid/js/jquery.jqGrid.src.js', 'lib/jqGrid/js/i18n/grid.locale-cn.js', 'build/ebaui.web/DataGrid.js'];
  filename = "ebaui.datagrid.js";
  if (cat["js"] == null) {
    cat["js"] = {
      files: {}
    };
  }
  if (cat["js"]['files'] == null) {
    cat["js"]['files'] = {};
  }
  jsfiles = cat["js"]['files'];
  jsfiles["build/" + filename] = js;
  jsfiles["../release/" + (grunt.config('pkg.version')) + "/" + filename] = js;
  return grunt.config('concat', cat);
};
