// Generated by CoffeeScript 1.7.1
module.exports = function(grunt) {

  /*
  *   javascript
   */
  var cat, datagrid, jsfiles, lib, treeview, _ref;
  lib = ['lib/jquery.min.js', 'lib/json2.js', 'lib/moment.js', 'lib/jqUI/jquery-ui.js', 'lib/loadmask/jquery.loadmask.js', 'lib/SWFUpload/swfupload.js', 'lib/SWFUpload/plugins/swfupload.cookies.js', 'lib/SWFUpload/plugins/swfupload.queue.js', 'lib/SWFUpload/plugins/swfupload.speed.js', 'lib/SWFUpload/plugins/swfupload.swfobject.js', 'lib/vex/vex.js', 'lib/vex/vex.dialog.js'];
  datagrid = ['lib/jqGrid/js/jquery.jqGrid.src.js', 'src/ebaui.DataGrid.js'];
  treeview = ['lib/jqZtree/jquery.ztree.all-3.5.js', 'src/ebaui.TreeView.js'];
  cat = (_ref = grunt.config('concat')) != null ? _ref : {};
  if (cat["js"] == null) {
    cat["js"] = {
      files: {}
    };
  }
  if (cat["js"]['files'] == null) {
    cat["js"]['files'] = {};
  }
  jsfiles = cat["js"]['files'];
  jsfiles['build/ebaui.lib.js'] = lib;
  jsfiles["../release/" + (grunt.config('pkg.version')) + "/ebaui.lib.js"] = lib;
  return grunt.config('concat', cat);
};
