// Generated by CoffeeScript 1.7.1
module.exports = function(grunt) {
  return grunt.registerTask('demo', 'generate ui demos', function() {
    var api, ctrls, item, layout, res, _i, _len, _results;
    ctrls = grunt.file.expand({
      filter: 'isDirectory',
      cwd: 'demo'
    }, '*');
    api = grunt.file;
    _results = [];
    for (_i = 0, _len = ctrls.length; _i < _len; _i++) {
      item = ctrls[_i];
      res = api.read("demo/" + item + "/res.inc");
      layout = "<!DOCTYPE html>\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n    <title>{{title}}</title>\n    {{res}}\n</head>\n<body>{{content}}</body>\n</html>";
      _results.push(api.recurse("demo/" + item + "/", function(abspath, rootdir, subdir, filename) {
        var cake, content, ext, file, html, title;
        cake = filename.substr(0, filename.length - 5);
        ext = filename.substring(filename.indexOf('.'));
        if (ext === ".inc") {
          return;
        }
        if (ext === ".layout") {
          return layout = api.read(abspath);
        }
        file = "build/demo/" + (item.toLowerCase()) + "_" + cake + ".html";
        title = "" + item + " " + cake;
        content = api.read(abspath);
        html = layout.replace('{{title}}', title).replace('{{res}}', res).replace('{{content}}', content);
        return api.write(file, html);
      }));
    }
    return _results;
  });
};
