// Generated by CoffeeScript 1.7.1
module.exports = function(grunt) {
  var cat, css, cssfiles, cssname, filename, js, jsfiles, _ref;
  css = ['lib/jqUILayout/layout-default.css'];
  cat = (_ref = grunt.config('concat')) != null ? _ref : {};
  if (cat["css"] == null) {
    cat["css"] = {
      files: {}
    };
  }
  cssname = "ebaui.uilayout.css";
  cssfiles = cat["css"]['files'];
  cssfiles["build/css/" + cssname] = css;
  cssfiles["../release/" + (grunt.config('pkg.version')) + "/css/" + cssname] = css;
  js = ['lib/jqUILayout/jquery.layout.js', 'build/ebaui.web/UiLayout.js'];
  filename = "ebaui.uilayout.js";
  if (cat["js"] == null) {
    cat["js"] = {
      files: {}
    };
  }
  if (cat["js"]['files'] == null) {
    cat["js"]['files'] = {};
  }
  jsfiles = cat["js"]['files'];
  jsfiles["build/" + filename] = js;
  jsfiles["../release/" + (grunt.config('pkg.version')) + "/" + filename] = js;
  return grunt.config('concat', cat);
};
